/**
 * The Fill in the blank sentence for every word in `src/data/symbol-vocabulary.ts`: one plain, natural sentence
 * with the blank inside it (the owner's style, see `checkFillStyle` in `rules.ts`). A word with two meanings has
 * a second key named after its category hint, for example "orange (color)". `profiles.ts` joins these to each
 * word's profile; a test checks that every word has one and every sentence passes the rules.
 */
export const vocabularyFill: Record<string, string> = {
  // Greetings
  hi: "I say ____ when my friend waves at me.",
  bye: "I say ____ when my friend gets on the bus.",
  "good afternoon": "I say ____ to my teacher after lunch.",
  "good night": "I say ____ to my family at bedtime.",
  "good evening": "I say ____ to Grandpa when the sun goes down.",
  "excuse me": "I say ____ when I need to walk past someone.",
  welcome: "We say ____ to the new student in our class.",
  "see you": "I tell my friend, ____ tomorrow!",
  "nice to meet you": "I say ____ when I meet someone new.",
  "how are you": "I ask ____ when I want to know if Grandma is well.",

  // Feelings
  mad: "I feel ____ when my brother breaks my crayon.",
  afraid: "I feel ____ when I hear a strange noise at night.",
  sleepy: "I feel ____ when it is time for bed.",
  bad: "I feel ____ when I break a cup.",
  good: "I feel ____ when I help my friend.",
  okay: "I feel ____ after my small cut stops hurting.",
  fine: "I feel ____ now that I am not sick anymore.",
  excited: "I feel ____ because we visit the zoo tomorrow.",
  bored: "I feel ____ when I have nothing to do.",
  worried: "I feel ____ when my pet is sick.",
  nervous: "I feel ____ when I sing in front of the class.",
  calm: "I feel ____ when I breathe slowly.",
  upset: "I feel ____ when my drawing gets torn.",
  frustrated: "I feel ____ when my puzzle piece will not fit.",
  shy: "I feel ____ when I meet many new people.",
  proud: "I feel ____ when I finish a hard puzzle.",
  surprised: "I feel ____ when my friends jump out and shout.",
  confused: "I feel ____ when I do not understand the steps.",
  lonely: "I feel ____ when no one plays with me.",
  silly: "I feel ____ when I make funny faces.",
  grumpy: "I feel ____ when I wake up too early.",
  jealous: "I feel ____ when my sister gets a new toy.",
  embarrassed: "I feel ____ when everyone laughs after I trip.",
  love: "I ____ my family very much.",
  like: "I ____ my friend because she is kind.",
  hungry: "I feel ____ when my tummy rumbles.",
  thirsty: "I feel ____ when my mouth is dry.",
  cold: "I feel ____, so I put on my jacket.",
  pain: "I am in ____ because I hurt my leg.",
  ill: "I stay in bed because I am ____.",
  better: "I feel ____ after I take my medicine.",
  unwell: "I feel ____ when my head and tummy hurt.",
  cry: "I ____ when I fall and hurt my knee.",
  laugh: "I ____ when my friend tells a funny joke.",
  smile: "I ____ when I see my family at the gate.",

  // People
  me: "Please throw the ball to ____.",
  my: "I carry ____ lunch box to school.",
  mine: "The red cup with my name is ____.",
  your: "Is this ____ pencil?",
  he: "My brother runs fast, and ____ wins the race.",
  she: "My sister is kind, and ____ shares her toys.",
  we: "____ play tag with our friends at recess.",
  they: "The birds sit on the wire, and ____ sing.",
  it: "I have a new ball, and ____ is red.",
  mom: "My ____ and I read a book at night.",
  mum: "I give my ____ a kiss before school.",
  mummy: "I run to my ____ after school.",
  dad: "My ____ and I play at the park.",
  daddy: "I read a book with my ____ at bedtime.",
  parent: "My ____ comes to school to meet my teacher.",
  brother: "My ____ and I share a room.",
  sister: "My big ____ helps me tie my shoes.",
  baby: "The ____ drinks milk from a bottle.",
  grandmother: "I visit my ____ on Sunday.",
  grandma: "I give ____ a hug when I visit her.",
  grandfather: "My ____ tells me stories from long ago.",
  grandpa: "I visit ____ at his house.",
  aunt: "My ____ visits us with my cousins.",
  uncle: "My ____ comes to my birthday party.",
  cousin: "I play with my ____ at Grandma's house.",
  family: "I live with my ____ in our house.",
  boy: "Ben is a ____ in my class.",
  girl: "Ana is a ____ in my class.",
  man: "The ____ at the store gives me my change.",
  woman: "A ____ helps me cross the road.",
  child: "I am a ____, and I go to school.",
  children: "The ____ play together in the park.",
  people: "Many ____ wait at the bus stop.",
  doctor: "The ____ checks me when I am sick.",
  nurse: "The ____ gives me a shot at the clinic.",
  police: "The ____ officer keeps our town safe.",
  principal: "The ____ talks to our whole school.",
  classmate: "My ____ and I learn in the same class.",
  helper: "The class ____ gives out the crayons.",
  neighbor: "Our ____ lives in the house next door.",

  // Food
  snack: "I eat a small ____ at recess.",
  breakfast: "I eat my ____ in the morning.",
  lunch: "We eat ____ at school at noon.",
  dinner: "My family eats ____ together at night.",
  meal: "We sit at the table for our ____.",
  toast: "I eat warm ____ with butter.",
  sandwich: "I bring a ham ____ for lunch.",
  egg: "I eat a boiled ____ for breakfast.",
  chicken: "We eat fried ____ for dinner.",
  "chicken (animal)": "The ____ on the farm lays eggs.",
  fish: "We eat grilled ____ with rice.",
  "fish (animal)": "A ____ swims in the water.",
  meat: "We cook ____ on the grill.",
  pork: "We have ____ adobo for lunch.",
  beef: "We eat ____ stew for dinner.",
  hotdog: "I eat a ____ in a bun.",
  burger: "I eat a ____ with cheese.",
  pizza: "We share a big ____ at the party.",
  pasta: "We cook ____ in a pot of water.",
  noodles: "I slurp my ____ from the bowl.",
  spaghetti: "I eat ____ with red sauce at the party.",
  soup: "I eat warm ____ with a spoon.",
  cereal: "I eat ____ with milk for breakfast.",
  cheese: "I put ____ on my sandwich.",
  butter: "I spread ____ on my bread.",
  jam: "I spread sweet ____ on my toast.",
  biscuit: "I eat a ____ with my tea.",
  cookie: "I eat a chocolate chip ____.",
  cake: "I blow out the candles on my birthday ____.",
  candy: "I unwrap a sweet ____.",
  chocolate: "I eat a bar of ____.",
  "ice cream": "I lick my cold ____ cone.",
  chips: "I eat salty ____ from the bag.",
  fries: "I eat ____ with my burger.",
  crackers: "I eat ____ with cheese for my snack.",
  yogurt: "I eat cold ____ with a spoon.",
  fruit: "I eat ____ because it is healthy.",
  apple: "I bite into a crunchy red ____.",
  orange: "I squeeze an ____ to make juice.",
  mango: "I eat a sweet yellow ____.",
  grapes: "I eat a bunch of purple ____.",
  pineapple: "The ____ has a spiky skin.",
  watermelon: "I eat a big red slice of ____.",
  strawberry: "I eat a small red ____.",
  papaya: "I eat orange ____ with black seeds.",
  vegetable: "A carrot is a ____.",
  carrot: "The rabbit eats a long orange ____.",
  potato: "We mash a ____ for dinner.",
  tomato: "I put a red ____ in my salad.",
  corn: "I eat yellow ____ on the cob.",
  peas: "I eat small green ____ with a spoon.",
  salad: "I eat a bowl of green ____.",
  sugar: "I put ____ in my tea to make it sweet.",
  salt: "I put ____ on my fries.",
  full: "My tummy is ____ after a big lunch.",
  yummy: "This soup tastes ____!",
  delicious: "The cake tastes so ____.",

  // Drinks
  juice: "I drink orange ____ at breakfast.",
  tea: "I sip warm ____ from a small cup.",
  coffee: "Grown-ups drink hot ____ in a mug.",
  "chocolate milk": "I drink cold ____ with my snack.",
  soda: "I drink fizzy ____ at the party.",
  cup: "I drink my water from a ____.",
  bottle: "I fill my water ____ before school.",
  glass: "I pour milk into a ____.",

  // Actions
  "sit down": "I ____ on my chair when class starts.",
  "stand up": "I ____ from my chair when the bell rings.",
  watch: "I ____ my show on TV.",
  draw: "I ____ a house with my crayons.",
  color: "I ____ the picture with my crayons.",
  paint: "I ____ a picture with my brush.",
  cut: "I ____ the paper with scissors.",
  glue: "I ____ the two papers together.",
  go: "We ____ across the road when the light is green.",
  come: "I ____ to my teacher when she calls me.",
  "come here": "My teacher says, ____, and I walk to her.",
  walk: "I ____ slowly in the hallway.",
  run: "I ____ very fast in the race.",
  jump: "I ____ over the puddle.",
  hop: "I ____ on one foot like a bunny.",
  climb: "I ____ up the ladder to the slide.",
  dance: "I ____ when the music plays.",
  sing: "I ____ happy birthday to my friend.",
  play: "I ____ with my friends at recess.",
  work: "I ____ quietly at my desk.",
  give: "I ____ my friend a pencil.",
  take: "I ____ a sticker from the teacher.",
  get: "I ____ my water bottle from my bag.",
  put: "I ____ my toys in the box.",
  open: "I ____ the door for my friend.",
  close: "I ____ the window when it is windy.",
  push: "I ____ my friend on the swing.",
  pull: "I ____ my wagon behind me.",
  throw: "I ____ the ball to my friend.",
  catch: "I ____ the ball with two hands.",
  kick: "I ____ the ball into the goal.",
  "wake up": "I ____ when my alarm rings.",
  wash: "I ____ my plate with soap.",
  brush: "I ____ my hair in the morning.",
  "brush teeth": "I ____ before I go to bed.",
  bath: "I take a warm ____ in the tub.",
  shower: "I take a quick ____ after sports.",
  dress: "I ____ in my school uniform.",
  "dress (clothes)": "I wear a pretty ____ to the party.",
  "get dressed": "I ____ before I go to school.",
  cook: "We ____ dinner in the kitchen.",
  clean: "I ____ my messy room.",
  "tidy up": "I ____ my toys after I play.",
  "line up": "We ____ at the door when the bell rings.",
  share: "I ____ my snack with my friend.",
  turn: "I wait for my ____ on the slide.",
  "my turn": "I waited, and now it is ____.",
  "your turn": "I tell my friend it is ____ on the swing.",
  finish: "I ____ my work before recess.",
  done: "My puzzle is ____, so I put it away.",
  start: "We ____ the race when the teacher says go.",
  again: "Let us sing that song ____!",
  need: "I ____ my umbrella when it rains.",
  have: "I ____ a red ball in my hand.",
  make: "I ____ a tall tower with blocks.",
  see: "I ____ the moon at night.",
  hear: "I ____ the bell with my ears.",
  talk: "I ____ to my friend at lunch.",
  say: "I ____ thank you when I get a gift.",
  tell: "I ____ my class a story.",
  ask: "I ____ my teacher a question.",
  answer: "I ____ the phone when it rings.",
  point: "I ____ at the bird with my finger.",
  show: "I ____ my drawing to my teacher.",
  think: "I ____ hard about the puzzle.",
  know: "I ____ how to count to ten.",
  learn: "I ____ new things at school.",
  count: "I ____ my blocks one by one.",
  find: "I ____ my pencil under my desk.",
  hide: "I ____ behind a tree when we play.",
  carry: "I ____ my bag to class.",
  fall: "I ____ down when I trip on a rock.",
  "sit quietly": "We ____ during story time.",
  "be quiet": "Please ____ when the baby sleeps.",
  clap: "I ____ my hands when my friend wins.",
  wave: "I ____ at my friend across the street.",
  hug: "I ____ Grandma when she visits.",
  kiss: "I ____ my baby sister on the cheek.",
  swim: "I ____ in the pool.",
  ride: "I ____ my bike to the park.",
  drive: "My family will ____ to the beach in our car.",
  fly: "Birds ____ high in the sky.",
  buy: "I ____ a snack at the store.",
  pay: "I ____ for my snack with money.",
  call: "I ____ Grandma on the phone.",

  // Small words
  not: "A mouse is ____ big.",
  was: "Yesterday I ____ sick.",
  be: "Please ____ kind to your friends.",
  do: "I ____ my homework at home.",
  can: "Birds ____ fly.",
  will: "Tomorrow I ____ go to the park.",
  the: "Please close ____ door.",
  and: "I have a cat ____ a dog.",
  or: "Do you want milk ____ juice?",
  with: "I go to the park ____ my family.",
  for: "This picture is ____ you.",
  to: "I walk ____ school every day.",
  in: "My toy is ____ the box.",
  on: "My cup is ____ the table.",
  under: "My shoe is ____ the bed.",
  up: "The balloon goes ____ into the sky.",
  down: "I go ____ the slide fast.",
  here: "I say I am ____ when my teacher calls my name.",
  there: "The ball is over ____ by the tree.",
  this: "____ toy in my hand is mine.",
  that: "____ car far away is red.",
  what: "____ is your name?",
  where: "____ is my bag?",
  who: "____ is at the door?",
  when: "____ is the party?",
  why: "____ are you sad?",
  how: "____ are you today?",
  which: "____ cup is yours?",
  all: "I ate ____ of my rice.",
  some: "I want ____ grapes, please.",
  many: "There are ____ stars in the sky.",
  less: "I have ____ milk than my brother.",
  same: "My shirt and your shirt are the ____ color.",
  different: "A cat and a dog are ____ animals.",
  now: "Please come here right ____.",
  later: "I will play ____ after my homework.",
  first: "I wash my hands ____, then I eat.",
  next: "I am ____ in line for the swing.",
  then: "I wash my hands, ____ I eat lunch.",
  last: "Ben is ____ in line.",
  before: "I wash my hands ____ I eat.",
  after: "I play outside ____ lunch.",
  today: "____ is my birthday.",
  tomorrow: "____ we will go to the zoo.",
  yesterday: "____ I went to the park.",
  morning: "I eat breakfast in the ____.",
  afternoon: "I take a nap in the ____.",
  night: "I sleep at ____.",
  time: "The clock tells me it is ____ to go home.",

  // Needs
  bathroom: "I wash my hands in the ____.",
  potty: "My baby brother sits on his ____.",
  pee: "I drank lots of water, and now I need to ____.",
  poo: "I sit on the toilet to ____.",
  tissue: "I wipe my runny nose with a ____.",
  medicine: "I take my ____ when I am sick.",
  break: "I eat my snack during the ____.",
  quiet: "I stay ____ in the library.",
  noise: "The drum makes a loud ____.",
  loud: "The drum is very ____.",
  safe: "I wear my seatbelt to stay ____.",
  careful: "I am ____ when the floor is wet.",
  emergency: "We call for help in an ____.",

  // Describing
  big: "An elephant is very ____.",
  small: "An ant is very ____.",
  little: "The baby has ____ hands.",
  long: "A snake has a ____ body.",
  short: "My pencil is ____ now.",
  tall: "The giraffe is very ____.",
  fast: "The race car goes very ____.",
  slow: "The turtle is very ____.",
  warm: "My blanket keeps me ____.",
  wet: "My clothes are ____ from the rain.",
  dry: "The towel is ____ after it hangs in the sun.",
  dirty: "My hands are ____ after I play in the mud.",
  soft: "My pillow is ____.",
  hard: "The rock is ____.",
  heavy: "My bag full of books is ____.",
  light: "A feather is very ____.",
  new: "I got ____ shoes today.",
  old: "Grandpa's hat is very ____.",
  empty: "My cup is ____ because I drank my juice.",
  closed: "The store is ____ at night.",
  nice: "My friend is ____ to me.",
  pretty: "The flowers in the garden are ____.",
  ugly: "The old broken box looks ____.",
  funny: "The clown is ____.",
  easy: "This puzzle is ____ for me.",
  difficult: "This big puzzle is ____ for me.",
  right: "Two plus two is four, so my answer is ____.",
  wrong: "I said two plus two is five, and I was ____.",
  dark: "The room is ____ when the lights are off.",
  bright: "The sun is very ____.",
  broken: "My toy is ____ because it fell.",

  // Colors
  red: "A ripe strawberry is ____.",
  blue: "The clear sky is ____.",
  yellow: "A ripe banana is ____.",
  green: "The fresh grass is ____.",
  purple: "The grapes are ____.",
  pink: "The flamingo is ____.",
  black: "The night sky is ____.",
  white: "The fluffy clouds are ____.",
  brown: "A chocolate bar is ____.",
  gray: "An elephant is ____.",
  grey: "A rain cloud is ____.",
  gold: "The shiny crown is ____.",
  silver: "The shiny spoon is ____.",
  "orange (color)": "A carrot is ____.",

  // Numbers
  one: "I have ____ nose.",
  two: "I have ____ eyes.",
  three: "A triangle has ____ sides.",
  four: "A dog has ____ legs.",
  five: "I have ____ fingers on one hand.",
  six: "An ant has ____ legs.",
  seven: "A week has ____ days.",
  eight: "A spider has ____ legs.",
  nine: "I count seven, eight, then ____.",
  ten: "I have ____ fingers on my two hands.",
  zero: "The empty jar has ____ cookies.",
  number: "Five is a ____.",

  // Shapes
  circle: "A ball is round like a ____.",
  square: "A ____ has four sides that are the same.",
  triangle: "A ____ has three sides.",
  rectangle: "A door is shaped like a ____.",
  star: "I see a bright ____ in the night sky.",
  heart: "I draw a ____ to show love.",
  shape: "A circle is a ____.",

  // Body
  body: "I wash my whole ____ in the bath.",
  head: "I wear a hat on my ____.",
  hair: "I comb my ____ every morning.",
  face: "I wash my ____ every morning.",
  eyes: "I see with my ____.",
  eye: "I close one ____ to wink.",
  ears: "I hear with my ____.",
  ear: "I whisper in my friend's ____.",
  nose: "I smell flowers with my ____.",
  mouth: "I eat and talk with my ____.",
  teeth: "I brush my ____ after I eat.",
  tongue: "I taste my food with my ____.",
  neck: "I wear a scarf around my ____.",
  shoulder: "I tap my friend on the ____.",
  arm: "I raise my ____ to ask a question.",
  hand: "I hold my spoon in my ____.",
  hands: "I clap my ____ to cheer.",
  finger: "I point with my ____.",
  tummy: "My ____ rumbles when I am hungry.",
  stomach: "My food goes down to my ____.",
  back: "I carry my bag on my ____.",
  leg: "I kick the ball with my ____.",
  knee: "I bend my ____ when I sit down.",
  foot: "I put a shoe on my ____.",
  feet: "I wear socks on my ____.",
  toes: "I wiggle my ____ in my socks.",

  // Clothes
  clothes: "I put on my ____ in the morning.",
  shirt: "I button up my ____.",
  "t-shirt": "I wear a ____ with short sleeves.",
  pants: "I wear long ____ to cover my legs.",
  shorts: "I wear ____ on a hot day.",
  skirt: "I wear a ____ that swings when I twirl.",
  uniform: "I wear my school ____ every day.",
  jacket: "I zip up my ____ when it is cold.",
  coat: "I wear a warm ____ on cold days.",
  hat: "I wear a ____ in the sun.",
  cap: "I wear a ____ to shade my eyes.",
  shoes: "I put on my ____ before I go out.",
  socks: "I wear ____ under my shoes.",
  slippers: "I wear soft ____ at home.",
  bag: "I put my books in my ____.",

  // School
  school: "I go to ____ to learn.",
  class: "The bell rings, and ____ starts.",
  classroom: "My desk is in my ____.",
  book: "I read a ____ with many pictures.",
  pencil: "I sharpen my ____ before I write.",
  pen: "I write in ink with a ____.",
  crayon: "I color with a red ____.",
  paper: "I draw on white ____.",
  scissors: "I cut paper with ____.",
  eraser: "I rub out my mistake with an ____.",
  ruler: "I draw a straight line with a ____.",
  desk: "I sit at my ____ in class.",
  table: "We eat dinner at the ____.",
  chair: "I sit on a ____.",
  board: "My teacher writes on the ____.",
  computer: "I type on the ____.",
  tablet: "I tap the screen of my ____.",
  homework: "I do my ____ at home after school.",
  lesson: "My teacher teaches us a ____ about plants.",
  story: "My teacher reads us a ____ about a bear.",
  song: "We sing a ____ in music class.",
  music: "We dance to the ____.",
  art: "We paint and draw in ____ class.",
  recess: "We play outside at ____.",
  playground: "We play on the swings at the ____.",
  library: "I borrow books from the ____.",
  line: "We stand in a ____ at the door.",
  "circle time": "We sit on the mat for ____.",

  // Home
  home: "I go ____ after school.",
  house: "My family lives in a ____.",
  room: "I clean my ____ on Saturday.",
  bedroom: "My bed is in my ____.",
  kitchen: "We cook food in the ____.",
  bed: "I sleep in my ____ at night.",
  door: "I knock on the ____.",
  window: "I look out the ____.",
  tv: "I watch cartoons on ____.",
  television: "We watch the news on the ____.",
  phone: "I talk to Grandma on the ____.",
  sofa: "We sit on the ____ to watch TV.",
  blanket: "I sleep under a warm ____.",
  pillow: "I rest my head on my ____.",
  toothbrush: "I clean my teeth with my ____.",
  soap: "I wash my hands with ____.",
  towel: "I dry my body with a ____.",
  plate: "I put my rice on a ____.",
  bowl: "I eat my soup from a ____.",
  spoon: "I eat rice with a ____.",
  fork: "I pick up my food with a ____.",
  knife: "Grown-ups cut the meat with a ____.",

  // Places and rides
  park: "We have a picnic at the ____.",
  shop: "We buy things at the ____.",
  store: "I buy milk at the ____.",
  market: "We buy fresh fish at the ____.",
  church: "My family prays at ____ on Sunday.",
  hospital: "Very sick people stay in the ____.",
  clinic: "I get a checkup at the ____.",
  outside: "We play ____ when it is sunny.",
  inside: "We play ____ when it rains.",
  garden: "Flowers grow in the ____.",
  beach: "I play in the sand at the ____.",
  zoo: "I see lions at the ____.",
  car: "My family rides in our ____.",
  bus: "I ride the school ____.",
  jeepney: "We ride a ____ to the market.",
  tricycle: "I ride a ____ to school.",
  train: "The ____ runs on the tracks.",
  bike: "I ride my ____ with two wheels.",
  boat: "The ____ floats on the water.",
  plane: "The ____ flies high in the sky.",
  road: "Cars drive on the ____.",

  // Toys
  toy: "I play with my ____ in my room.",
  ball: "I kick the ____ to my friend.",
  doll: "I hold my ____ like a baby.",
  blocks: "I build a tower with ____.",
  puzzle: "I put the ____ pieces together.",
  game: "We play a ____ with dice.",
  bubbles: "I blow ____ in the yard.",
  "car toy": "I push my ____ across the floor.",
  teddy: "I hug my ____ bear at night.",
  kite: "I fly my ____ in the wind.",
  swing: "I go back and forth on the ____.",
  slide: "I zoom down the ____.",
  crayons: "I keep my ____ in a box.",

  // Animals
  animal: "A dog is an ____.",
  dog: "The ____ barks and wags its tail.",
  cat: "The ____ says meow.",
  bird: "The ____ sings in the tree.",
  cow: "The ____ says moo.",
  pig: "The ____ rolls in the mud.",
  horse: "I ride a ____ on the farm.",
  duck: "The ____ swims in the pond.",
  sheep: "The ____ has soft wool.",
  goat: "The ____ eats grass on the farm.",
  rabbit: "The ____ hops and has long ears.",
  mouse: "The tiny ____ says squeak.",
  monkey: "The ____ climbs the tree.",
  lion: "The ____ roars loudly.",
  tiger: "The ____ has black stripes.",
  elephant: "The ____ has a long trunk.",
  bear: "The ____ eats honey.",
  frog: "The green ____ hops and says ribbit.",
  snake: "The ____ has no legs.",
  butterfly: "The ____ flies to the flowers.",
  bee: "The ____ buzzes and makes honey.",
  ant: "The tiny ____ walks in a line.",

  // Weather
  weather: "We check the ____ before we go out.",
  sun: "The ____ shines in the day.",
  sunny: "It is ____ today, so I wear my hat.",
  rain: "I use my umbrella in the ____.",
  rainy: "I stay inside on a ____ day.",
  cloud: "A white ____ floats in the sky.",
  cloudy: "The sky is ____, and I cannot see the sun.",
  wind: "The ____ blows my kite up high.",
  windy: "My hat blows away on a ____ day.",
  storm: "We stay inside during the ____.",
  thunder: "I hear ____ in the storm.",
  "hot day": "I sweat a lot on a ____.",
  "cold day": "I wear my jacket on a ____.",
  moon: "I see the ____ at night.",
  sky: "Birds fly in the ____.",

  // Gestures
  "eat food": "I am hungry, so I want to ____.",
  "drink water": "I am thirsty, so I want to ____."
};
