import { normalizePecsLabel } from "@/data/pecs-card-manifest";

const fillBlankPromptByLabel: Record<string, string> = {
  hello: "Say ____ when greeting someone.",
  goodbye: "Say ____ when leaving.",
  "good morning": "Say ____ at the start of the day.",
  "thank you": "Say ____ when someone helps you.",
  please: "Say ____ when asking nicely.",
  sorry: "Say ____ after a mistake.",
  happy: "I feel ____.",
  sad: "I feel ____.",
  angry: "I feel ____.",
  scared: "I feel ____.",
  tired: "I feel ____.",
  sick: "I feel ____.",
  i: "____ want a turn.",
  you: "I am talking to ____.",
  mother: "My ____ is here.",
  father: "My ____ is here.",
  teacher: "My ____ helps me learn.",
  friend: "I play with my ____.",
  eat: "I want to ____.",
  drink: "I want to ____.",
  food: "I want ____.",
  water: "I want ____.",
  rice: "I want ____.",
  bread: "I want ____.",
  milk: "I want ____.",
  banana: "I want ____.",
  sit: "Please ____.",
  stand: "Please ____.",
  listen: "Please ____.",
  look: "Please ____.",
  read: "I can ____ a book.",
  write: "I can ____.",
  wait: "Please ____.",
  stop: "Please ____.",
  toilet: "I need the ____.",
  help: "I need ____.",
  rest: "I need a ____.",
  sleep: "I want to ____.",
  "wash hands": "I need to ____.",
  more: "I want ____.",
  finished: "I am ____.",
  danger: "This is ____.",
  hot: "This is ____.",
  hurt: "I am ____.",
  yes: "Answer ____ when it is right.",
  no: "Answer ____ when it is not right.",
  want: "I ____ a turn.",
  am: "I ____ happy.",
  is: "It ____ my turn.",
  are: "You ____ here."
};

export function createFillBlankPromptForLabel(label: string) {
  const normalized = normalizePecsLabel(label);
  return fillBlankPromptByLabel[normalized] ?? `Choose ____ for ${label}.`;
}
